### PR TITLE
Revert "[Fix][Shade] Relocate Jackson in seatunnel-hadoop-aws to match the uber jar (#11673)"

### PR DESCRIPTION
**Pull request by hawk9821**
This reverts commit 2586f37e96dff5a80be0065d020c8830dde96b00.

NOTE: This is an intentional revert, not a mistake.

## Background

PR #11673 relocated Jackson in the `seatunnel-hadoop-aws` module to match the uber jar's namespace. However, the `seatunnel-shade` module has been migrated to a separate repository: [apache/seatunnel-shade](https://github.com/apache/seatunnel-shade).

## Reason for Revert

Since `seatunnel-shade` is no longer a submodule of this repository (`apache/seatunnel`):
- Modifications to the shade module made within this repo (including the Jackson relocation in #11673) are no longer effective
- Changes to the shade module should be submitted to the standalone repository: [apache/seatunnel-shade](https://github.com/apache/seatunnel-shade)
- Keeping the changes from #11673 would cause inconsistencies between this repo and the standalone shade repo

## Follow-up

If the Jackson relocation fix is still needed, please submit the change to:
https://github.com/apache/seatunnel-shade

## Related

- Reverts #11673

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/developer/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Review by DanielLeens — CHANGES_REQUESTED** [review]
# What Problem Does This PR Solve?

This PR reverts commit `2586f37e96` ([Fix][Shade] Relocate Jackson in `seatunnel-hadoop-aws` to match the uber jar, #11673, merged 2026-08-13). The stated reason is that `seatunnel-shade` "has been migrated to a separate repository" (`apache/seatunnel-shade`) and is "no longer a submodule of this repository", so changes made to it inside `apache/seatunnel` are claimed to be ineffective and would drift from the standalone repo.

That premise does not hold against the current `dev` HEAD, and that is the crux of this review. `seatunnel-shade` was never a git submodule of `apache/seatunnel` (`.gitmodules` on `dev` only lists two `.github/actions/*` submodules), and it is still today a normal, actively-built Maven module in this repo:

- `pom.xml:56` on `dev` still declares `<module>seatunnel-shade</module>` in the root reactor.
- `seatunnel-shade/seatunnel-hadoop-aws/pom.xml` inherits `<version>${revision}</version>` from the `seatunnel-shade` parent — i.e. it is versioned and built in lockstep with the rest of the repo, not resolved from an externally published coordinate.
- It is a real, consumed dependency: `seatunnel-connectors-v2/connector-file/connector-file-s3/pom.xml` and `seatunnel-dist/pom.xml` depend on `org.apache.seatunnel:seatunnel-hadoop-aws`, and it is bundled into the official binary distribution via `seatunnel-dist/src/main/assembly/assembly-seatunnel-bin*.xml`.
- The actual proposal to remove this module and delegate it to `apache/seatunnel-shade` is **PR #9993** ("[Feature][shade] Refactor the seatunnel-shade module"), opened 2025-10-29 and **still OPEN/unmerged** (last updated today, 2026-08-18). No such migration has landed on `dev`.
- `git log` on `seatunnel-shade/seatunnel-hadoop-aws/pom.xml` shows #11673's commit (2026-08-13) as the most recent change to that file — nothing has touched it since to reflect any migration.

So, as things stand on `dev`, reverting #11673 does not undo an ineffective no-op change; it removes a working, verified fix and reintroduces the exact runtime defect #11673 documented: `seatunnel-hadoop-aws` is shaded without relocating Jackson, while `seatunnel-hadoop3-*-uber` (which supplies `hadoop-common`'s `JsonSerialization`) relocates it. The method descriptors disagree, and any `fs.s3a.assumed.role.*` configuration on the S3A path fails at runtime with `NoSuchMethodError: org.apache.hadoop.util.JsonSerialization.getMapper()`. #11673 reproduced this with `javap` evidence (before: 3 classes under `org/apache/hadoop/` referencing the original package; after: 0), so this is not a theoretical concern.

# 1. Code Change Review

## 1.1 Core Logic Analysis

The diff is a byte-for-byte inverse of #11673 across all three files it touched:

- `seatunnel-shade/seatunnel-hadoop-aws/pom.xml`: removes the `<relocation>` block that maps `com.fasterxml.jackson` → `${seatunnel.shade.package}.hadoop.com.fasterxml.jackson` inside the `maven-shade-plugin` execution, along with its explanatory comment.
- `tools/dependencies/check_shaded_jackson_refs.py`: deletes the regression-check script entirely (161 lines) — the tool that scans every class under `org/apache/hadoop/` in the built jar for lingering references to the original, unrelocated Jackson package.
- `.github/workflows/backend.yml`: removes the "Check shaded Jackson references" CI step that ran this script against the built `seatunnel-hadoop-aws.jar`, and removes `seatunnel-shade/**` from the path list that triggers full API-coverage CI runs.

Mechanically this is a clean, complete revert — there is no partial/inconsistent state; all three files return exactly to their pre-#11673 content. That part of the execution is correct.

The problem is not mechanical, it is substantive: this reverts a real fix for a real `NoSuchMethodError` and removes the only CI signal that would catch it again, while the PR's own justification for doing so does not match the current state of the `dev` branch (see above). No alternative fix, tracking issue link, or evidence of an actual regression caused by #11673 is provided in the PR body — only the (incorrect) claim that the change is a no-op.

## 1.2 Compatibility Impact

**Incompatible** relative to the current `dev` state (post-#11673). Concretely:

- Any user running `seatunnel-hadoop-aws` (bundled into the official `seatunnel-dist` binary, consumed by `connector-file-s3`) with `fs.s3a.assumed.role.*` configured will hit `NoSuchMethodError` on `JsonSerialization.getMapper()` again, exactly as documented in #11673 and issue #11655 that it closed.
- Relative to the pre-#11673 state, this PR is of course a "compatible" restoration in the narrow sense of matching old bytes — but that old state is the one with the confirmed bug, so "compatible with the buggy baseline" is not a meaningful improvement.
- No entry in `docs/en/introduction/concepts/incompatible-changes.md` is added, which is arguably correct if this is treated as a pure revert, but it also means there is no documented trail explaining to users why assumed-role S3A support regressed again between the version containing #11673 and the version containing this revert.

## 1.3 Performance / Side-Effect Analysis

Negligible performance impact either way — this is metadata-only shading configuration. The side effect that matters is functional, not performance: silently reintroducing a runtime crash path (see 1.2) and removing automated detection of it.

## 1.4 Error Handling and Logging

Not applicable — no runtime error-handling or logging code is touched.

### Issue 1
- **Location**: PR description (top-level rationale), and by extension `seatunnel-shade/seatunnel-hadoop-aws/pom.xml` (the relocation being removed) and `tools/dependencies/check_shaded_jackson_refs.py` (deleted)
- **Problem**: The PR's stated justification — "`seatunnel-shade` is no longer a submodule of this repository" and "modifications... made within this repo... are no longer effective" — is factually incorrect against current `dev`. `.gitmodules` never listed `seatunnel-shade`; `pom.xml` still declares `<module>seatunnel-shade</module>`; `seatunnel-hadoop-aws` still builds with `${revision}` in lockstep with the rest of the reactor and is still consumed by `connector-file-s3` and packaged into `seatunnel-dist`. The actual migration proposal, PR #9993, is still open and unmerged as of today.
- **Potential risk**: Merging this PR silently reintroduces the `NoSuchMethodError` on `fs.s3a.assumed.role.*` paths that #11673 fixed and documented with reproducible `javap` evidence, in the officially distributed `seatunnel-dist` binary, with zero replacement fix in `dev` and zero CI signal left to catch it (the regression script is deleted, not just disabled).
- **Best improvement**: Do not merge this revert against `dev` as-is. If the real intent is "wait until #9993 lands and then drop the in-repo shade module entirely," that should happen atomically with #9993 (or after it merges), not as a standalone revert that leaves the module in place but bug-affected. If there is a genuine, verified problem with #11673's relocation (e.g. it breaks something else observed in production), that needs to be stated with concrete evidence in the PR body, and the fix should be replaced rather than blindly removed — e.g. by fast-tracking #11648 (Hadoop 3.4.3 / AWS SDK v2 migration) if that is meant to supersede it, or by re-adding the relocation once #9993's migration is actually in place.
- **Severity**: High
- **Raised by another reviewer**: No

# 2. Code Quality Assessment

## 2.1 Coding Standards
The diff itself is clean (it is a pure revert), so there is nothing to flag on style/formatting grounds.

## 2.2 Test Coverage and Test Stability
This PR *removes* the only regression test for this defect class (`tools/dependencies/check_shaded_jackson_refs.py`, wired into the `Dependency licenses` CI job). Per project policy, removing or disabling an existing test/check without a replacement, and without evidence the underlying issue no longer applies, is a regression in test strictness and should be treated as a blocker on its own — independent of the functional bug being reintroduced.

## 2.3 Documentation Updates
No documentation changes are included or required for a pure revert; not a defect on its own, but see Issue 1 regarding the missing evidence trail for why the fix is being pulled.

# 3. Architectural Soundness

## 3.1 Elegance of the Solution
This is a **temporary/blind workaround at best**, not a fix: it removes a targeted, well-documented, reproducible bug fix and its regression check based on a premise (submodule migration already in effect) that is not true on `dev` today. A revert PR needs either (a) hard evidence the original fix caused a real regression, or (b) confirmation that the thing it "duplicates" has actually landed elsewhere. Neither is present here.

## 3.2 Maintainability
Reduces maintainability: the well-commented relocation rule and the well-documented regression-check script (both of which explain a genuinely subtle link-time descriptor mismatch) are deleted outright rather than, say, gated behind the pending #9993 migration.

## 3.3 Extensibility
N/A — no new extension points introduced or removed beyond the above.

## 3.4 Historical-Version Compatibility
Users upgrading from a version built after #11673 (2026-08-13) to a version built after this revert would silently regress on any S3A assumed-role configuration — a functional break with no changelog/incompatible-changes entry, which the project's own "any incompatible change MUST be documented" rule would normally require if this revert is intentional and justified. Since I do not believe it is justified given current `dev` state, that gap is secondary to Issue 1, but worth noting if the revert is ultimately deemed correct for reasons not yet stated in the PR.

# 4. Issue Summary

| Number | Issue | Location | Severity |
|---|---|---|---|
| 1 | Revert's stated justification ("seatunnel-shade migrated out, changes here are ineffective") is contradicted by current `dev` state (`pom.xml:56`, `.gitmodules`, still-open #9993); merging reintroduces the `NoSuchMethodError` #11673 fixed on `fs.s3a.assumed.role.*` paths in the officially distributed binary, with no replacement fix and the regression-detecting CI check deleted outright | `seatunnel-shade/seatunnel-hadoop-aws/pom.xml`, `tools/dependencies/check_shaded_jackson_refs.py`, `.github/workflows/backend.yml`, PR description | High |

# 5. Merge Recommendation

### Conclusion: Not recommended for merge

1. **Blockers — must be fixed**
   - Issue 1 (High): The revert's premise does not hold against current `dev`. `seatunnel-shade` is still an in-repo, actively-built, actively-consumed Maven module (root `pom.xml:56`, `${revision}`-versioned, depended on by `connector-file-s3` and `seatunnel-dist`), and the actual removal proposal (#9993) is still open. Before this can merge, the PR needs to either (a) present concrete evidence that #11673's relocation itself broke something in production/CI that outweighs restoring the `NoSuchMethodError`, or (b) be sequenced correctly with #9993 so the module (and this now-redundant fix) is removed together, not left half-migrated with the bug back in place. As-is, merging this PR reintroduces a confirmed runtime crash on the S3A assumed-role path with no CI safety net left behind.

2. **Recommended fixes — non-blocking**
   - If a genuine reason to revert #11673 exists that I have not been able to verify from the repository state alone (e.g. an internal decision to accelerate the #9993 migration this week), please state it explicitly in the PR body with a link/timeline, since the current wording reads as a straightforward factual error about the module's status.
   - If the intent is really "supersede via #11648" (Hadoop 3.4.3 / AWS SDK v2 upgrade), that PR is also still open/unmerged, so there would be a gap between this revert landing and #11648 landing during which the bug is unguarded; consider not reverting until #11648 (or another concrete fix) is actually merged.

**Overall assessment**: This is a mechanically clean revert, but the justification given for it is verifiably false against the current `dev` branch, based on direct inspection of `.gitmodules`, the root `pom.xml` module list, the `seatunnel-hadoop-aws` module's own `pom.xml` (parent version `${revision}`), its real consumers (`connector-file-s3`, `seatunnel-dist`), and the still-open state of PR #9993 (the actual shade-module migration proposal). I was not able to find any linked issue, production incident, or CI failure caused by #11673 that would independently justify this revert — if such evidence exists outside what's visible in the PR/issue trackers, it should be added to the PR description; I'm flagging this as a verified factual gap in the stated rationale, not merely a stylistic concern, since merging as-is reinstates a documented `NoSuchMethodError` in the officially distributed S3A binary with no replacement and no regression check left in CI.

**Review by davidzollo — APPROVED** [review]
+1
LGTM
Thanks for your contribution!

**Comment by DanielLeens** [comment]
@davidzollo thanks for taking a look, and I don't want to be the one holding up a contributor's PR without cause — but I need to push back here rather than let this pass quietly, since I noticed the merge already happened a few seconds after your approval.

I re-verified my concern directly against the merge commit itself (`f415ed8e52630444bfc3a40d0b8fc7c3a38051ab`, now on `dev`), not just the PR diff, to make sure nothing had changed since my review yesterday:

- `pom.xml` on the merged `dev` HEAD still declares `<module>seatunnel-shade</module>` (line 56) — it is still an in-repo, in-lockstep-versioned (`${revision}`) Maven module, not an externally published dependency.
- The actual migration proposal to pull `seatunnel-shade` out into its own repo, #9993, is still **open and unmerged** as of right now.
- The merge diff is confirmed to be the exact inverse of #11673: it removes the `com.fasterxml.jackson` → `${seatunnel.shade.package}.hadoop.com.fasterxml.jackson` relocation from `seatunnel-shade/seatunnel-hadoop-aws/pom.xml`, and deletes `tools/dependencies/check_shaded_jackson_refs.py` outright (not just disables it).

So the stated rationale for the revert ("seatunnel-shade is no longer a submodule here, changes are ineffective") is still factually incorrect against current `dev`, and this has now merged. Concretely, that means `dev` currently reintroduces the `NoSuchMethodError` on `org.apache.hadoop.util.JsonSerialization.getMapper()` that #11673 fixed (reproduced there with `javap` evidence), for anyone using `fs.s3a.assumed.role.*` with the officially distributed `seatunnel-hadoop-aws` jar — and the CI check that would have caught this is gone, not just green.

Since it's already merged, I'm not asking to block anymore — I'm asking for a prompt follow-up: either revert this revert until #9993 actually lands, or re-apply the Jackson relocation (and ideally restore the regression script) in a new PR. Happy to be shown I've misread something, but the module list and #9993's open state are both directly checkable right now, so if I'm wrong about the premise I'd like to understand where.

**Comment by loustler** [comment]
@hawk9821 @davidzollo — closing the loop on this one.

The revert asked for the Jackson relocation to be resubmitted to apache/seatunnel-shade. Done: **apache/seatunnel-shade#20**, first commit.

It's in the same PR as the Hadoop 3.4.3 / AWS SDK v2 upgrade rather than standing alone, because both touch `seatunnel-shade-hadoop-aws` and both land on the same release coordinate (`3.4.3-3.0.0`). On its own the relocation had no coordinate to ship under — `3.1.4-3.0.0` is already published.

I verified there that the fix still does what it did here: `seatunnel-shade-hadoop3-uber` relocates `com.fasterxml.jackson` to `${seatunnel.shade.package}.hadoop.com.fasterxml.jackson`, so `JsonSerialization#getMapper` returns the relocated `ObjectMapper`, and after the change `RoleModel`'s call site in the built jar carries the matching descriptor.
