### PR TITLE
[Feature][Client] Python SDK Client for SeaTunnel REST API

### PR DESCRIPTION
**Pull request by davidzollo**
### Purpose of this pull request

This PR revives and supersedes #10184.

The original contributor commit chain from @luciobvjr is kept intact on this branch, and this follow-up only adds one additional fix commit to address the pending review blockers.

It updates the Python SDK work in three areas:

- align the installation docs with the current reality that the SDK is not published to PyPI yet
- keep the SDK compatible with Python 3.9 by replacing Python 3.10-only union annotations
- add regression tests for request construction, error wrapping, context-manager cleanup, and overview query forwarding

### Does this PR introduce any user-facing change?

Yes.

- the Python SDK docs now describe a real source-install flow instead of `pip install seatunnel`
- the SDK keeps working on Python 3.9 as declared in `setup.py`
- the cluster overview helper now forwards filter query parameters to the REST API

### How was this patch tested?

- `python3 -m pip install --target /tmp/seatunnel-sdk-pr10184-install ./tools/seatunnel-python-sdk`
- `PYTHONPATH=tools/seatunnel-python-sdk:/tmp/seatunnel-sdk-pr10184-install python3 -m unittest discover -s tools/seatunnel-python-sdk/tests`
- `./mvnw spotless:apply`
- `./mvnw -q -DskipTests verify`
- `./mvnw test -q` (fails in `seatunnel-config-shade` with a pre-existing `NoClassDefFoundError` for shaded `ConfigFactory`, unrelated to this PR's files)

### CODE REVIEW

**Comment by davidzollo** [comment]
Closing this duplicate PR because the same fix has been pushed back to the original PR #10184.
