### ISSUE TITLE
[Bug] [seatunnel-connectors-v2] java.lang.NoClassDefFoundError: org/apache/spark/sql/connector/write/Write

### ISSUE THREAD

**Issue by 981433814** [apache/seatunnel#4879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel 2.3.1 An error occurs when the spark Engine is Used. The spark version is 3.1.2

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }

}

sink {
  Console {
  }

}
```

### Running Command

```shell
./bin/start-seatunnel-spark-3-connector-v2.sh \
--master local[1] \
--deploy-mode client \
--config ./config/v2.batch.config.template
```

### Error Exception

```log
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/connector/write/Write
        at org.apache.seatunnel.translation.spark.sink.SeaTunnelSinkTable.newWriteBuilder(SeaTunnelSinkTable.java:59)
        at org.apache.spark.sql.execution.datasources.v2.BatchWriteHelper.newWriteBuilder(WriteToDataSourceV2Exec.scala:321)
        at org.apache.spark.sql.execution.datasources.v2.BatchWriteHelper.newWriteBuilder$(WriteToDataSourceV2Exec.scala:316)
        at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.newWriteBuilder(WriteToDataSourceV2Exec.scala:218)
        at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.run(WriteToDataSourceV2Exec.scala:225)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.doExecute(V2CommandExec.scala:55)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
        at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:370)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
        at org.apache.seatunnel.core.starter.spark.execution.SinkExecuteProcessor.execute(SinkExecuteProcessor.java:125)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:74)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:60)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.connector.write.Write
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang
```

### Flink or Spark Version

spark-3.1.2-bin-hadoop2.7

### Java or Scala Version

java 1.8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/45874392/eea22431-743a-4184-8f64-eefd87c5dc36)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by exxiang** [comment]
Have you tried placing Spark's jar in the connectors directory？

**Comment by 981433814** [comment]
I have tried putting spark-core and spark-sql under the seatunnel lib package and plugin, nothing works


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/seatunnel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/seatunnel] [Bug] [seatunnel-connectors-v2] java.lang.NoClassDefFoundError: org/apache/spark/sql/connector/write/Write (Issue #4879)





 
Have you tried placing Spark's jar in the connectors directory？

**Comment by exxiang** [comment]
My version is apache-seatunnel-incubating-2.3.1 and spark-3.4.0-bin-hadoop3, my work is ok,You can try setting SPARK_HOME

**Comment by mdsoss** [comment]
I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write

**Comment by 981433814** [comment]
> I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write

Can you import jar packages instead of upgrading spark

**Comment by mdsoss** [comment]
> > I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write
> 
> Can you import jar packages instead of upgrading spark

I also want to try to just import the jar package, but it has not been successful so far. I try to move the relevant spark jars package to the seatunnel/lib directory. I can see that the spark-submit command is read, but it does not solve the problem.

**Comment by CheneyYin** [comment]
> I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write

Since spark 3.2.0, `buildForBatch` and `buildForStreaming` have been deprecated in `org.apache.spark.sql.connector.write.WriteBuilder`. So you should keep spark version >= `3.2.0`.

**Comment by 981433814** [comment]
> > I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write
> 
> Since spark 3.2.0, `buildForBatch` and `buildForStreaming` have been deprecated in `org.apache.spark.sql.connector.write.WriteBuilder`. So you should keep spark version >= `3.2.0`.

Does seatunnel consider compatibility with spark 3.1.2

**Comment by CheneyYin** [comment]
> > > I also ran into this problem, my spark version is 3.1.3, after upgrading to 3.3.2, the problem was solved, I looked at spark-sql_2.12-3.1.3.jar and spark-sql_2.12-3.3.2 .jar, version 3.1.3 did not have org.apache.spark.sql.connector.write.Write
> > 
> > Since spark 3.2.0, `buildForBatch` and `buildForStreaming` have been deprecated in `org.apache.spark.sql.connector.write.WriteBuilder`. So you should keep spark version >= `3.2.0`.
> 
> Does seatunnel consider compatibility with spark 3.1.2

PTAL @TyrantLucifer
